name: CI - Google Test

on:
  push:
    branches:
      - master  # principale branch
  pull_request:
    branches:
      - master  # principale branch for pull requests

jobs:
  build-and-test:
    runs-on: windows-latest  # using Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5  # setup NuGet to restore packages

    - name: Restore NuGet packages
      run: nuget restore src/src.sln

    - name: Build solution
      run: msbuild src/src.sln

    - name: Run tests
      run: src/x64/Debug/unit_tests.exe

